# Generated by Django 6.0.6 on 2026-07-09 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefamodel',
            old_name='titulo',
            new_name='assunto',
        ),
        migrations.RenameField(
            model_name='tarefamodel',
            old_name='concluida',
            new_name='status',
        ),
    ]
